export AwakenAlt from './AwakenAlt';
export BrandIconAlt from './BrandIconAlt';
export ConnectAlt from './ConnectAlt';
export DiscoverAlt from './DiscoverAlt';
export FavoriteAlt from './FavoriteAlt';
export HomeAlt from './HomeAlt';
export LocationAlt from './LocationAlt';
export MoreAlt from './MoreAlt';
export TimeAlt from './TimeAlt';
